import {
  faFacebook,
  faGithub,
  faInstagram,
  faLinkedinIn,
  faNpm,
  faTwitter,
  faWordpressSimple,
} from '@fortawesome/free-brands-svg-icons'
import {
  faArrowUp,
  faBars,
  faCertificate,
  faCheck,
  faExternalLinkAlt,
  faFileCode,
  faInbox,
  faLanguage,
  faMagnet,
  faServer,
  faTasks,
  faWrench,
} from '@fortawesome/free-solid-svg-icons'

export const icons = {
  faTwitter,
  faFacebook,
  faInstagram,
  faGithub,
  faNpm,
  faWordpressSimple,
  faLinkedinIn,
  faInbox,
  faFileCode,
  faServer,
  faTasks,
  faLanguage,
  faMagnet,
  faCertificate,
  faExternalLinkAlt,
  faCheck,
  faWrench,
  faArrowUp,
  faBars,
}
